### ISSUE TITLE
The documented PLEXIL commit leads to a failure of building ow_autonomy (melodic-devel branch)

### ISSUE THREAD

**Issue by oceank** [nasa/ow_simulator#181]
**Description of the build failure**:
by following the [installation document](https://github.com/nasa/ow_simulator/blob/melodic-devel/oceanwaters/doc/setup_dev_env.md),  it complains that class PLEXIL::ExecApplication has no member named 'allPlansFinished' when building the ow_autonomy package.

**Detailed error in the output**:
src/ow_autonomy/ow_plexil/src/plexil-adapter/OwExecutive.cpp:48:20: error: ‘class PLEXIL::ExecApplication’ has no member named ‘allPlansFinished’; did you mean ‘waitForPlanFinished’?
  return PlexilApp->allPlansFinished();

**Cause & Fix**:
The error is caused by using the incorrect PLEXIL code. In [installation document](https://github.com/nasa/ow_simulator/blob/melodic-devel/oceanwaters/doc/setup_dev_env.md), it is suggested to use the PLEXIL code with the tag, "OceanWATERS-v7.1", which does not contain the definition of the method, 'allPlansFinished'. By updating the PLEXIL code to the most recent commit and rebuilding PLEXIL, the above build failure can be fixed.

**Comment by kmdalal** [comment]
Sorry for the delayed reply.  The install instructions on GitHub are for Release 8 or the 'master' branch of the ow_autonomy repository.   There were changes since that do indeed require a newer Plexil.   Everything will be in sync when Release 9 is completed.  

I believe the requirement for the newer Plexil was included in one of our weekly email updates, but in the future, we'll also put it in the relevant README files.

**Comment by oceank** [comment]
@kmdalal Thanks for the clarification. I probably missed it in email updates.
