### ISSUE TITLE
Bug: power faults on ArmMoveCartesian

### ISSUE THREAD

**Issue by kmdalal** [nasa/ow_simulator#340]
Got strange power faults (and the first instantaneous capacity loss I've ever seen) when running a modified version of the `TestArmMoveCartesianGuarded` plan. 

This is on the branch `power-faults-arm-move-cartesian`

In the Plexil terminal:
```
Enter any additional plan to be run (or use the GUI): 
[ INFO]: PLEXIL: Beginning TestMoveCartesian...
[ INFO]: ArmUnstow () started...
[ INFO]: ArmUnstow finished in state SUCCEEDED
[ INFO]: Starting ArmMoveCartesian (frame=0, relative=0)
[ INFO]: ArmMoveCartesian () started...
[ WARN]: Fault in SYSTEM: POWER_EXECUTION_ERROR
[ WARN]: Fault in POWER: INSTANTANEOUS_CAPACITY_LOSS
[ WARN]: Resolved fault in SYSTEM: POWER_EXECUTION_ERROR
[ WARN]: Resolved fault in POWER: INSTANTANEOUS_CAPACITY_LOSS
[ WARN]: Fault in SYSTEM: POWER_EXECUTION_ERROR
[ WARN]: Fault in POWER: INSTANTANEOUS_CAPACITY_LOSS
[ WARN]: Fault in POWER: LOW_STATE_OF_CHARGE
[ WARN]: Resolved fault in SYSTEM: POWER_EXECUTION_ERROR
[ WARN]: Resolved fault in POWER: INSTANTANEOUS_CAPACITY_LOSS
[ WARN]: Resolved fault in POWER: LOW_STATE_OF_CHARGE
^C[identify_sample_location-3] killing on exit
[terminal_selection_node-2] killing on exit
[ow_exec_node-1] killing on exit
[terminal_selection_node-2] escalating to SIGTERM
shutting down processing monitor...
... shutting down processing monitor complete
done
```
The only two SOC values I saw (the simulator seemed to freeze after this).
```
$ rostopic echo /battery_state_of_charge 
WARNING: no messages received and simulated time is active.
Is /clock being published?
header: 
  seq: 54
  stamp: 
    secs: 1916524915
    nsecs: 789999962
  frame_id: ''
value: -10.033720970153809
---
header: 
  seq: 55
  stamp: 
    secs: 1916524917
    nsecs: 832499981
  frame_id: ''
value: 0.8583303689956665
---
```
The simulator terminal output looked normal.

**Comment by Lumsterling** [comment]
I don't see a branch titled ``power-faults-move-arm-cartesian``. Was it deleted some time ago?

**Comment by kmdalal** [comment]
I can't find that branch either, even locally.  It's possible it's on my other Ubuntu machine at the office, which I won't go back to until next Wednesday.

I'd say we should just close this issue, given how old it is, and that the environment was a development branch that has now been merged.   We can open a Jira if we see the problem again.

**Comment by Lumsterling** [comment]
I'm seeing the problem behavior on ``noetic-devel``, actually, so I'm not certain about closing this. I ran ``TestArmMoveCartesianGuarded.plx`` on there and the power faults occur as well. However, I'm seeing a *lot* of questionable behavior with that specific test plan...

The plan will just freeze up (the real-time factor dropped all the way to ``0.01`` in the last run) only to suddenly overcome whatever what causing the whole simulation to hang after 1-2 minutes, and when the system eventually recovers the arm goes flying. It's at these moments the instantaneous capacity loss & low state-of-charge faults get triggered, I would guess due to an extreme power load applied for a brief moment (even with the invalid ``jointStatesCb`` behavior in the development branch, the power input still spiked at 93W at one point which requires extremely high joint state values). I'm not really familiar with what ``TestArmMoveCartesianGuarded``'s behavior is supposed to look like, but I can't imagine this is expected.

**Comment by kmdalal** [comment]
Thanks @Lumsterling for investigating this further.  Please open a Jira for this so we can track it better in our sprints.  Then close this issue.   I suggest demoing this plan next Dev Day, since both @AstroStucky and @Hao12450 may have insights.
